require('plugins.autopairs')
require('plugins.bufferline')
require('plugins.colorizer')
require('plugins.galaxyline')
require('plugins.gitsigns')
require('plugins.nvimtree')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.toggleterm')
require('plugins.lspzero')
require('plugins.undotree')

